import { Card } from "../types/Card.js";
export const characterPack: { [key: string]: Card[] } = {
  "tara-pack": [
    {
      cardName: "Lamp Lighter",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "lamp_lighter",
      cardDescription: "When play this card, deal 1 damage to random enemy.",
      cardType: "minion",
      cardImageName: "lamp_lighter",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tripplewick Trickster",
      cardSkills: [{ type: "DealRandomEnemy", amount: 2 }],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "tripplewick_trickster",
      cardDescription: "When play this card, deal 2 damage to random enemy.",
      cardType: "minion",
      cardImageName: "tripplewick_trickster",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Saloon Brewmaster",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 2 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "saloon_brewmaster",
      cardDescription: "When play this, draw a card.",
      cardType: "minion",
      cardImageName: "saloon_brewmaster",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Flame Revenant",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "flame_revenant",
      cardDescription: "When play this, give random minion 1/1.",
      cardType: "minion",
      cardImageName: "flame_revenant",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Spontaneous",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 2,
      cardAttack: 1,
      cardHealth: 1,
      image: "spontaneous_combustion",
      cardImageName: "spontaneous_combustion",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Solar Flare",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 5,
      cardAttack: 1,
      cardHealth: 1,
      image: "solar_flare",
      cardImageName: "solar_flare",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tidepool Pupil",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      image: "tidepool_pupil",
      cardImageName: "tidepool_pupil",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Redgill Razorjaw",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "redgill_razorjaw",
      cardImageName: "redgill_razorjaw",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Unchained Gladiator",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 4,
      image: "unchained_gladiator",
      cardImageName: "unchained_gladiator",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Raid Leader",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "raid_leader",
      cardImageName: "raid_leader",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Gorgonzormu",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 3,
      image: "gorgonzormu",
      cardImageName: "gorgonzormu",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Shield Master",
      cardSkills: [{ type: "GiveArmor", amount: 4 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "shield_master",
      cardImageName: "shield_master",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "boulderfist_ogre",
      cardImageName: "boulderfist_ogre",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "dread_corsair",
      cardImageName: "dread_corsair",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Lamp Lighter",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "lamp_lighter",
      cardDescription: "When play this card, deal 1 damage to random enemy.",
      cardType: "minion",
      cardImageName: "lamp_lighter",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tripplewick Trickster",
      cardSkills: [{ type: "DealRandomEnemy", amount: 2 }],
      cardCost: 4,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "tripplewick_trickster",
      cardDescription: "When play this card, deal 2 damage to random enemy.",
      cardType: "minion",
      cardImageName: "tripplewick_trickster",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Saloon Brewmaster",
      cardSkills: [{ type: "ReturnToHandAndGiveHealth", amount: 2 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "saloon_brewmaster",
      cardDescription: "When play this, draw a card.",
      cardType: "minion",
      cardImageName: "saloon_brewmaster",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Flame Revenant",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 1 }],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 3,
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      image: "flame_revenant",
      cardDescription: "When play this, give random minion 1/1.",
      cardType: "minion",
      cardImageName: "flame_revenant",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Spontaneous Combustion",
      cardSkills: [{ type: "DealRandomEnemy", amount: 4 }],
      cardCost: 2,
      cardAttack: 1,
      cardHealth: 1,
      image: "spontaneous_combustion",
      cardImageName: "spontaneous_combustion",
      cardDescription: "When play this, give 4 damage to random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Solar Flare",
      cardSkills: [{ type: "DealAllEnemy", amount: 2 }],
      cardCost: 5,
      cardAttack: 1,
      cardHealth: 1,
      image: "solar_flare",
      cardImageName: "solar_flare",
      cardDescription: "When play this, deal 2 damage  to all enemies.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Tidepool Pupil",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 2,
      cardHealth: 2,
      image: "tidepool_pupil",
      cardImageName: "tidepool_pupil",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Redgill Razorjaw",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "redgill_razorjaw",
      cardImageName: "redgill_razorjaw",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Unchained Gladiator",
      cardSkills: [],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 4,
      image: "unchained_gladiator",
      cardImageName: "unchained_gladiator",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Raid Leader",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "raid_leader",
      cardImageName: "raid_leader",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Gorgonzormu",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 3,
      image: "gorgonzormu",
      cardImageName: "gorgonzormu",
      cardDescription: "",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Shield Master",
      cardSkills: [{ type: "GiveArmor", amount: 4 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "shield_master",
      cardImageName: "shield_master",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription: "When play this, give 4 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "boulderfist_ogre",
      cardImageName: "boulderfist_ogre",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Boulderfist Ogre",
      cardSkills: [{ type: "GiveArmor", amount: 2 }],
      cardCost: 3,
      cardAttack: 3,
      cardHealth: 4,
      image: "dread_corsair",
      cardImageName: "dread_corsair",
      cardDescription: "When play this, give 2 armor to your hero.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "tara-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
  "bhima-pack": [
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription:
        "When play this, gain health equal to the number of cards in your hand.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Dictator",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 3 }],
      cardCost: 3,
      cardAttack: 2,
      cardHealth: 3,
      image: "dictator",
      cardImageName: "dictator",
      cardDescription:
        "In an alternate reality, you chose the dark side and the wrong side. Empowers a card by 3.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Guitarist",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 2,
      image: "guitar",
      cardImageName: "guitar",
      cardDescription:
        "You make sounds and annoy the enemy. 'Ağğymm gonaswink from the şendılii'",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Paid Price",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 4,
      cardAttack: 1,
      cardHealth: 1,
      image: "soldier",
      cardImageName: "soldier",
      cardDescription:
        "After playing this card, your chance of finding a job increases by 50% and deals 1 damage to a random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Warrior",
      cardSkills: [{ type: "GiveArmor", amount: 3 }],
      cardCost: 5,
      cardAttack: 5,
      cardHealth: 4,
      image: "worrior",
      cardImageName: "worrior",
      cardDescription: "After playing the warrior card, gain 3 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Military Operation",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 4,
      cardHealth: 3,
      image: "asker",
      cardImageName: "asker",
      cardDescription:
        "Attacks the enemy with 7.62 mm, reducing each opponent's health by 1-3.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Hunter",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 2,
      image: "avci",
      cardImageName: "avci",
      cardDescription:
        "A master tracker, sets traps for the enemy and hunts with deadly arrows.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Cat",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 1,
      cardHealth: 9,
      image: "cat",
      cardImageName: "cat",
      cardDescription:
        "An agile and silent hunter. It seems to have turned into a cat and is no longer itself.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Easy Job",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 2,
      image: "dead",
      cardImageName: "dead",
      cardDescription: "You earn money lying down, oh I'm dead.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Detective",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      image: "dedektif",
      cardImageName: "dedektif",
      cardDescription:
        "Collects clues with each move, revealing the enemy's weak points.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Design",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 4,
      image: "design",
      cardImageName: "design",
      cardDescription:
        "When you read this book, you feel knowledge flowing into your mind.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kyk",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 1,
      image: "kyk",
      cardImageName: "kyk",
      cardDescription:
        "It makes those who see it lose their appetite, reducing each enemy's health!",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Miner",
      cardSkills: [],
      cardCost: 2,
      cardAttack: 3,
      cardHealth: 4,
      image: "madenci",
      cardImageName: "madenci",
      cardDescription:
        "Digs deep to search for treasure, overcoming obstacles with explosives.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Rohan Rider",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 5,
      cardHealth: 6,
      image: "parlamak",
      cardImageName: "parlamak",
      cardDescription:
        "A brave Rohan rider, attacks the enemy with speed and strength, gaining 5 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Last Supper",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 5,
      cardHealth: 3,
      image: "sonaksamyemegi",
      cardImageName: "sonaksamyemegi",
      cardDescription:
        "The last meal you had with your friends in the city, gains 3 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Twilight Drake",
      cardSkills: [{ type: "GainHealthAmountOfCardsInYourHand" }],
      cardCost: 4,
      cardAttack: 4,
      cardHealth: 5,
      image: "twilight_drake",
      cardImageName: "twilight_drake",
      cardDescription:
        "When play this, gain health equal to the number of cards in your hand.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Dictator",
      cardSkills: [{ type: "EmpowerRandomCard", amount: 3 }],
      cardCost: 3,
      cardAttack: 2,
      cardHealth: 3,
      image: "dictator",
      cardImageName: "dictator",
      cardDescription:
        "In an alternate reality, you chose the dark side and the wrong side. Empowers a card by 3.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Guitarist",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 2,
      image: "guitar",
      cardImageName: "guitar",
      cardDescription:
        "You make sounds and annoy the enemy. 'Ağğymm gonaswink from the şendılii'",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Paid Price",
      cardSkills: [{ type: "DealRandomEnemy", amount: 1 }],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 1,
      image: "soldier",
      cardImageName: "soldier",
      cardDescription:
        "After playing this card, your chance of finding a job increases by 50% and deals 1 damage to a random enemy.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Warrior",
      cardSkills: [{ type: "GiveArmor", amount: 3 }],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 9,
      image: "worrior",
      cardImageName: "worrior",
      cardDescription: "After playing the warrior card, gain 3 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Military Operation",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 4,
      cardHealth: 3,
      image: "asker",
      cardImageName: "asker",
      cardDescription:
        "Attacks the enemy with 7.62 mm, reducing each opponent's health by 1-3.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Hunter",
      cardSkills: [],
      cardCost: 3,
      cardAttack: 4,
      cardHealth: 2,
      image: "avci",
      cardImageName: "avci",
      cardDescription:
        "A master tracker, sets traps for the enemy and hunts with deadly arrows.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Cat",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 9,
      image: "cat",
      cardImageName: "cat",
      cardDescription:
        "An agile and silent hunter. It seems to have turned into a cat and is no longer itself.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Easy Job",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 1,
      cardHealth: 2,
      image: "dead",
      cardImageName: "dead",
      cardDescription: "You earn money lying down, oh I'm dead.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Detective",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 2,
      image: "dedektif",
      cardImageName: "dedektif",
      cardDescription:
        "Collects clues with each move, revealing the enemy's weak points.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Design",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 2,
      cardHealth: 4,
      image: "design",
      cardImageName: "design",
      cardDescription:
        "When you read this book, you feel knowledge flowing into your mind.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Kyk",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 1,
      image: "kyk",
      cardImageName: "kyk",
      cardDescription:
        "It makes those who see it lose their appetite, reducing each enemy's health!",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Miner",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 3,
      cardHealth: 4,
      image: "madenci",
      cardImageName: "madenci",
      cardDescription:
        "Digs deep to search for treasure, overcoming obstacles with explosives.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Rohan Rider",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 5,
      cardHealth: 6,
      image: "parlamak",
      cardImageName: "parlamak",
      cardDescription:
        "A brave Rohan rider, attacks the enemy with speed and strength, gaining 5 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
    {
      cardName: "Last Supper",
      cardSkills: [],
      cardCost: 1,
      cardAttack: 5,
      cardHealth: 3,
      image: "sonaksamyemegi",
      cardImageName: "sonaksamyemegi",
      cardDescription:
        "The last meal you had with your friends in the city, gains 3 armor.",
      cardOwner: "player",
      profile: null,
      borderColor: null,
      isSelected: false,
      isPlayedLastTurn: false,
      cardId: Math.random(),
      cardPack: "bhima-pack",
      cardType: "minion",
      deg: 0,
      move: 0,
      boardPairId: null,
    },
  ],
};
